[package]
name = "inf1-jup-interface"
edition.workspace = true
license-file.workspace = true
version.workspace = true
include = ["src/**/*", "Cargo.toml"]

[dependencies]
anyhow = { workspace = true }
backoff = { workspace = true }
inf1-std = { workspace = true }
sanctum-lst-list = { workspace = true }
ureq = { workspace = true, features = ["gzip", "json", "rustls"] }

# solana-deps
# try not to use solana-sdk so that we can easily remove it in the future
solana-pubkey = { workspace = true }
solana-sha256-hasher = { workspace = true }
